### ISSUE TITLE
Final PDF show the progress bar and content overlaps following pages

### ISSUE THREAD

**Issue by akosma** [mfontanini/presenterm-export#4] opened 2024-01-23 14:24 UTC
After performing a PDF export of the demo slides on the [presenterm](https://github.com/mfontanini/presenterm) project, the resulting PDF (attached) shows the progress bar, and the contents are progressively "pushed" to the following pages, making only the first page appear more or less ok.

I understand this tool is still in its early stages, but just wanted to let you know. Using kitty as terminal under Fedora 39, IBM Plex font 14 pt.

[demo.pdf](https://github.com/mfontanini/presenterm-export/files/14025296/demo.pdf)

**Comment by mfontanini** [comment] 2024-01-23 15:01
This issue happened before and was fixed. Maybe it's come back... What version of presenterm and presenterm-exporter are you using?

**Comment by mfontanini** [comment] 2024-01-23 15:11
Also, what version of tmux are you using? I think the last time it was tmux breaking this

**Comment by akosma** [comment] 2024-01-24 13:03
I'm using the following versions:
- tmux next-3.4
- presenterm 0.4.1
- presenterm-export 0.2.0

**Comment by mfontanini** [comment] 2024-01-24 18:15
I built the latest tmux source code and I can't reproduce this so it may not be related to tmux. How did you get this exact version?

Using a larger font size also doesn't seem to cause this. I may need your help to debug this:

* Clone presenterm latest and cd into `presenterm`.
* Run the following:
```shell
cargo run -- --generate-pdf-metadata examples/demo.md
 | presenterm-export --emit-intermediate ./target/debug/presenterm ./examples/demo.md --export
```
* This will generate 2 files in examples, `demo.final.html` and `demo.pre.html`. If you could upload both of those here, that may help finding out what the issue is.

**Comment by akosma** [comment] 2024-01-25 08:22
Sure! Please find the files: [demo.zip](https://github.com/mfontanini/presenterm-export/files/14048853/demo.zip). 

For info, I've installed it on Fedora just using the standard "dnf install tmux" command. It brought this version.

**Comment by mfontanini** [comment] 2024-01-25 20:44
Thanks! I ended up installing fedora 39 in a vm and managed to reproduce it. I'm not sure what it is in that environment that causes the issue but it should be fixed in #5. Would you mind installing presenterm-export from that PR and try it? It should work, but just to be safe.

The issue is actually seen in the PDF you uploaded: you can see how there's a gap in between code block lines. That extra padding was pushing the length of each slide further than it should.

**Comment by akosma** [comment] 2024-01-26 09:36
Yes! It works 😄 I `pip install git+https://github.com/mfontanini/presenterm-export.git@refs/pull/5/head` and run the same `cargo run` command as above, and as shown in the attachment [demo.zip](https://github.com/mfontanini/presenterm-export/files/14063005/demo.zip), the PDF file is simply perfect. This is great! Thank you sooooo much for your help.

**Comment by akosma** [comment] 2024-01-26 15:04
BTW I used your tool for my slides in a conference talk yesterday, here they are: https://speakerdeck.com/akosma/managing-fleets-of-kubernetes-clusters-with-gitops – thanks a lot for such a great tool! Looking forward to using it in future presentations.

**Comment by mfontanini** [comment] 2024-01-26 15:10
Awesome, thanks for sharing and I'm glad the issue is fixed! Love to see people using the tool in conferences!

**Closed as completed** 2024-01-26 21:03 UTC

**Comment by orahcio** [comment] 2024-05-07 00:03
I saw this issue here, I use presenterm 0.4.1, presenterm-export 0.2.1 anda tmux 3.3a, I tried also with tmux 3.4

**Comment by mfontanini** [comment] 2024-05-07 01:51
Presenterm 0.4.1 is very outdated, you should upgrade :)

**Comment by orahcio** [comment] 2024-05-07 02:13
I did, presenterm 0.7.0. I built here whith some changes in the capture.py:  sum 3 on height (line 59) and comment lines 64 and 66. Maybe tmux on my system lies about the number of lines yet. I don't know why. The pdf file was genereted correctly only after these changes.
